---
- name: installed dependencies
  apt:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- name: added the Docker signing key
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/ubuntu/gpg ') }}"
    state: present

- name: added the Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: installed Docker
  apt:
  - docker-ce
  - docker-ce-cli
  - containerd.io
