---
- import_tasks: "{{ ansible_os_family|lower }}.yml"

- name: started Docker and enabled at boot
  service:
    name: docker
    state: started
    enabled: true

- name: added Jenkins to 'docker' group
  user:
    name: jenkins
    groups: docker
    append: true

- name: scheduled a clean up for Docker images
  become: true
  cron:
    user: root
    name: "docker-clean-up-images"
    minute: "0"
    hour: "22"
    job: "docker rmi $(docker images | awk '/^<none>/ { print $3 }') 2> /dev/null"
    day: "10"

- name: scheduled a clean up for Docker unused containers
  become: true
  cron:
    user: root
    name: "docker-clean-up-containers"
    minute: "0"
    hour: "22"
    job: "docker ps --filter 'status=exited' | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm 2> /dev/null"
    day: "5"
