---
- name: installed basic Jenkins slave dependencies
  yum:
    update_cache: true
    name:
    - git
    - java-1.8.0-openjdk
    - yum-utils
    - lvm2
    - device-mapper-persistent-data
    state: present

- name: restored SELinux context
  command: restorecon -v
  changed_when: false
  args:
    chdir: /home/jenkins
    creates: /home/jenkins/.ssh/id_rsa.pub
