---
- name: created Jenkins user
  user:
    name: jenkins
    state: present

- name: added SSH key for Jenkins master
  authorized_key:
    user: jenkins
    state: present
    key: "{{ jenkins_openssh_public_key }}"

- include_tasks: "{{ ansible_os_family|lower }}.yml"
