---
- hosts: "{{ UM_RUNNERS_GRP|default('runners') }}"
  tasks:
  - name: installed build dependencies
    apt:
      update_cache: true
      name:
      - gcc
      - python3-pip

      # Also install pip for python 2 -- although deprecated,
      # some Ansible modules do not work well with Python 3
      # yet (e.g. k8s_facts).
      - python-pip

  - name: installed common dependencies
    with_items:
    - pip3
    - pip2
    vars:
      packages:
      - lxml==4.3.4
      - requests==2.22.0
      - quantum-queen==1.0.3
      - openshift==0.9.0
    pip:
      state: present
      name: "{{ packages }}"
      executable: "{{ item }}"
