---
- hosts: "{{ UM_RUNNERS_GRP|default('runners') }}"
  tasks:
  - name: install dnf
    yum:
      state: present
      name: dnf

- hosts: "{{ UM_RUNNERS_GRP|default('runners') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: install build dependencies
    dnf:
      name: [gcc]

  - name: installed common dependencies
    vars:
      packages:
      - lxml==4.3.4
      - requests==2.22.0
      - quantum-queen==1.0.3
      - openshift==0.8.1
    pip:
      state: present
      name: "{{ packages }}"
