---
- hosts: "{{ UM_RUNNERS_GRP|default('runners') }}"
  tasks:
  - name: installed build dependencies
    apt:
      name:
      - gcc
      - python3-pip

  - name: installed common dependencies
    vars:
      packages:
      - lxml==4.3.4
      - requests==2.22.0
      - quantum-queen==1.0.3
      - openshift==0.9.0
    pip:
      state: present
      name: "{{ packages }}"
